baseURL = "https://keithzeng.github.io"
languageCode = "en-us"
title = "k317h"
theme = "maupassant"
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[author]
  name = "飞雪无情"

[params]
  author = "k317h"
  subtitle = "A blog to record my progress"
  keywords = "a,b,c"
  description = "????"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"

googleAnalytics = "UA-133234541-1"

[params.utteranc]  #check https://utteranc.es/
    enable = true
    repo = "keithzeng/blog"
    issueTerm = "pathname"
    theme = "github-light" #github-light vs github-dark
