baseURL = "https://keithzeng.github.io"
languageCode = "en-us"
title = "k317h"
theme = "maupassant"
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[author]
  name = "飞雪无情"

[params]
  author = "k317h"
  subtitle = "A blog to record my progress"
  keywords = "a,b,c"
  description = "????"

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

googleAnalytics = "UA-133234541-1"

[params.utteranc]  #check https://utteranc.es/
    enable = true
    repo = "keithzeng/blog"
    issueTerm = "pathname"
    theme = "github-light" #github-light vs github-dark
